#!/usr/bin/env python3

import os
api_key = 'klucz' #Klucz api umożliwiający prace z googlemaps API.
import googlemaps

gmaps = googlemaps.Client(key=api_key) #Za każdym wywołaniem funkcji z biblioteki googlemaps'a potrzebny jest klucz api.
mainnode = gmaps.geocode('Uniwersytet Wrocławski: Wydział Fizyki i Astronomii, Plac Maksa Borna, Wrocław')[0] # Sposób na wypisanie długości i szerokości geograficznych miejsc, które są potrzebne.
geocode_step1 = mainnode['geometry']['location'] #zwężanie wyszukiwań.
geocode_step2 = geocode_step1['lat'], geocode_step1['lng'] #wyciągniecie potrzebnych nam danych.
print (geocode_step2)
